classDiagram
    class HabitacionComponent {
        <<interface>>
        +getDescripcion() string
        +getCosto() number
    }

    class HabitacionEstandar {
        +getDescripcion() string
        +getCosto() number
    }

    class HabitacionDeluxe {
        +getDescripcion() string
        +getCosto() number
    }

    class Suite {
        +getDescripcion() string
        +getCosto() number
    }

    class ServicioDecorator {
        <<abstract>>
        #habitacion HabitacionComponent
        +ServicioDecorator(habitacion)
        +getDescripcion()* string
        +getCosto()* number
    }

    class DesayunoDecorator {
        +getDescripcion() string
        +getCosto() number
    }

    class WifiPremiumDecorator {
        +getDescripcion() string
        +getCosto() number
    }

    class VistaMarDecorator {
        +getDescripcion() string
        +getCosto() number
    }

    class JacuzziDecorator {
        +getDescripcion() string
        +getCosto() number
    }

    HabitacionComponent <|.. HabitacionEstandar
    HabitacionComponent <|.. HabitacionDeluxe
    HabitacionComponent <|.. Suite
    HabitacionComponent <|.. ServicioDecorator

    ServicioDecorator <|-- DesayunoDecorator
    ServicioDecorator <|-- WifiPremiumDecorator
    ServicioDecorator <|-- VistaMarDecorator
    ServicioDecorator <|-- JacuzziDecorator

    ServicioDecorator o-- HabitacionComponent : envuelve
